### ISSUE TITLE
demo will not allow the user to open a board

### ISSUE THREAD

**Issue by neu-ma-tic** [supabase-community/svelte-kanban#4]
# Bug report

## Describe the bug

demo will not allow the user to open a board

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. open the demo & login
2. select "create a board"
3. Your new board opens with no data

## Expected behavior

the board should open and allow me to add lists

## Screenshots

https://cdn.neu.lol/files/1057c6a3f959710d0ee7421a2e4995d4de290e801a8c4cef0490fcf02fcc8bc4.png

## System information

non applicable

## Additional context

query string:
```
select=id%2Ctitle%2Clists%28id%2Ctitle%2Cposition%2Ccards%28id%2Cdescription%2Cposition%29%29&id=eq.3968&order=position.asc.nullslast&%22lists%22.order=position.asc.nullslast&%22lists.cards%22.order=position.asc.nullslast
```
full response
```
{"message":"Cannot apply filter because 'lists.cards' is not an embedded resource in this request","hint":"Verify that 'lists.cards' is included in the 'select' query parameter."}
```

**Comment by avelican** [comment]
I was opening a new issue when I realized it was a duplicate of this one.
Posting the details here in case it helps.

---

# Bug report

## Description: app breaks when opening newly created board

```
Failed to load resource: the server responded with a status of 400 ()
Board.js:173 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'lists')
    at Array.Tt (Board.js:173:36)
    at Object.p (Board.js:518:73)
    at ct (index-0e089fc9.js:411:36)
    at it (index-0e089fc9.js:379:13)
```

## To Reproduce

1. Go to https://supabase-kanban.vercel.app/
2. Enter your email
3. Click the confirmation link 
App loads fine, no errors yet.
4. Click "add a board"
New board is created (appears on the main app page later).
However I see a blank blue page, no text or interactive content anywhere.
The error mentioned above appears in the console.

## Screenshots

How the app looks after clicking add new board: https://files.catbox.moe/91pmai.jpg

## System information

- OS: Windows 10 22H2 19045.2251
- Browser: Brave Browser 1.45.133 (Chromium 107.0.5304.141) 
(Same behavior observed in Firefox 107.0)

**Comment by elimisteve** [comment]
I am experiencing a similar issue, but a different error appears to be causing it:

```js
Uncaught (in promise) TypeError: t[1] is null                                                  Board.js:173:28
    Tt Board.js:173
    p Board.js:518
    ct index-0e089fc9.js:411
    it index-0e089fc9.js:379
```

**Comment by silentworks** [comment]
Sorry haven't updated this in a while, I'll do an update in the coming days and see if I can replicate the issue and fix it.

**Comment by silentworks** [comment]
I have fixed this issue if you run the project locally. I can't update the vercel link as the project was contributed by a community member who has moved on to working on other projects.

**Comment by sswam** [comment]
Thanks for fixing the issue, it would be good to update the README to mention that the demo is broken, or else remove the demo. Or, I might be able to provide another demo app link in a little while.

**Comment by hearsid** [comment]
#6 
Request admin to merge this PR, 
@silentworks @joshnuss

**Comment by joshnuss** [comment]
Happy to transfer ownership of hosting to @silentworks. It's hosted on vercel.
